#include "./addition.hpp"
#include "./convex.hpp"
#include "./invert.hpp"
#include "./scale.hpp"
#include "./subtract.hpp"
#include "./blend.hpp"
#include "./fix.hpp"
#include "./check.hpp"

#include "./operator.hpp"
