#include "./addition.hpp"
#include "./clamp.hpp"
#include "./convex.hpp"
#include "./invert.hpp"
#include "./scale.hpp"
#include "./subtract.hpp"
#include "./blend.hpp"
#include "./fix.hpp"
#include "./integrity.hpp"
#include "./overburn.hpp"

#include "./operator.hpp"
