#!/bin/bash

pwd

./LabCH2cmy.exe
./LabCH2cmyk.exe
./LabCH2gray.exe
./LabCH2hsi.exe
./LabCH2hsl.exe
./LabCH2hsv.exe
./LabCH2hwb.exe
./LabCH2lab.exe
./LabCH2LabCH.exe
./LabCH2lms.exe
./LabCH2lms_BFD.exe
./LabCH2lms_K65.exe
./LabCH2lms_KE.exe
./LabCH2lms_MCAT02.exe
./LabCH2luv.exe
./LabCH2LuvCH.exe
./LabCH2rgb.exe
./LabCH2xyy.exe
./LabCH2xyz.exe
./LabCH2YCgCo.exe
./LabCH2YDbDr.exe
./LabCH2yiq.exe
./LabCH2YPbPr.exe
./LabCH2YPbPr2020.exe
./LabCH2YPbPr601.exe
./LabCH2YPbPr709.exe
./LabCH2yuv.exe
./LabCH2yuv601.exe
./LabCH2yuv709.exe