#!/bin/bash

pwd

./cmyk2cmy.exe
./cmyk2cmyk.exe
./cmyk2gray.exe
./cmyk2hsi.exe
./cmyk2hsl.exe
./cmyk2hsv.exe
./cmyk2hwb.exe
./cmyk2lab.exe
./cmyk2LabCH.exe
./cmyk2lms.exe
./cmyk2lms_BFD.exe
./cmyk2lms_K65.exe
./cmyk2lms_KE.exe
./cmyk2lms_MCAT02.exe
./cmyk2luv.exe
./cmyk2LuvCH.exe
./cmyk2rgb.exe
./cmyk2xyy.exe
./cmyk2xyz.exe
./cmyk2YCgCo.exe
./cmyk2YDbDr.exe
./cmyk2yiq.exe
./cmyk2YPbPr.exe
./cmyk2YPbPr2020.exe
./cmyk2YPbPr601.exe
./cmyk2YPbPr709.exe
./cmyk2yuv.exe
./cmyk2yuv601.exe
./cmyk2yuv709.exe