
import nucleotide

#make setting
settings = nucleotide.Settings( )

#Accumulate 
# Nothing to accumulate. This is minimal

# Call
product = SConscript('./SConscript', exports=[ 'settings' ] )

#Make it defualt
Default( product )


