#!/bin/bash

pwd

./YPbPr2cmy.exe
./YPbPr2cmyk.exe
./YPbPr2gray.exe
./YPbPr2hsi.exe
./YPbPr2hsl.exe
./YPbPr2hsv.exe
./YPbPr2hwb.exe
./YPbPr2lab.exe
./YPbPr2LabCH.exe
./YPbPr2lms.exe
./YPbPr2lms_BFD.exe
./YPbPr2lms_K65.exe
./YPbPr2lms_KE.exe
./YPbPr2lms_MCAT02.exe
./YPbPr2luv.exe
./YPbPr2LuvCH.exe
./YPbPr2rgb.exe
./YPbPr2xyy.exe
./YPbPr2xyz.exe
./YPbPr2YCgCo.exe
./YPbPr2YDbDr.exe
./YPbPr2yiq.exe
./YPbPr2YPbPr.exe
./YPbPr2YPbPr2020.exe
./YPbPr2YPbPr601.exe
./YPbPr2YPbPr709.exe
./YPbPr2yuv.exe
./YPbPr2yuv601.exe
./YPbPr2yuv709.exe