#!/bin/bash

pwd

./YCgCo2cmy.exe
./YCgCo2cmyk.exe
./YCgCo2gray.exe
./YCgCo2hsi.exe
./YCgCo2hsl.exe
./YCgCo2hsv.exe
./YCgCo2hwb.exe
./YCgCo2lab.exe
./YCgCo2LabCH.exe
./YCgCo2lms.exe
./YCgCo2lms_BFD.exe
./YCgCo2lms_K65.exe
./YCgCo2lms_KE.exe
./YCgCo2lms_MCAT02.exe
./YCgCo2luv.exe
./YCgCo2LuvCH.exe
./YCgCo2rgb.exe
./YCgCo2xyy.exe
./YCgCo2xyz.exe
./YCgCo2YCgCo.exe
./YCgCo2YDbDr.exe
./YCgCo2yiq.exe
./YCgCo2YPbPr.exe
./YCgCo2YPbPr2020.exe
./YCgCo2YPbPr601.exe
./YCgCo2YPbPr709.exe
./YCgCo2yuv.exe
./YCgCo2yuv601.exe
./YCgCo2yuv709.exe