echo off
set  left_folder=..\out\extract
set  right_folder=..\..\..\..\mirror\example\test\out\extract
set  target_folder=..\out\check
set  program_TC=..\out\tc.exe


%program_TC% %left_folder%\black-hsl-1-000-alvy.tga                           %right_folder%\black-hsl-1-000-alvy.tga                                        %target_folder%\black-hsl-1-000-alvy.tga
%program_TC% %left_folder%\black-hsl-1-000-star.tga                           %right_folder%\black-hsl-1-000-star.tga                                        %target_folder%\black-hsl-1-000-star.tga
%program_TC% %left_folder%\black-hsl-1-025-alvy.tga                           %right_folder%\black-hsl-1-025-alvy.tga                                        %target_folder%\black-hsl-1-025-alvy.tga
%program_TC% %left_folder%\black-hsl-1-025-star.tga                           %right_folder%\black-hsl-1-025-star.tga                                        %target_folder%\black-hsl-1-025-star.tga
%program_TC% %left_folder%\black-hsl-1-050-alvy.tga                           %right_folder%\black-hsl-1-050-alvy.tga                                        %target_folder%\black-hsl-1-050-alvy.tga
%program_TC% %left_folder%\black-hsl-1-050-star.tga                           %right_folder%\black-hsl-1-050-star.tga                                        %target_folder%\black-hsl-1-050-star.tga
%program_TC% %left_folder%\black-hsl-1-075-alvy.tga                           %right_folder%\black-hsl-1-075-alvy.tga                                        %target_folder%\black-hsl-1-075-alvy.tga
%program_TC% %left_folder%\black-hsl-1-075-star.tga                           %right_folder%\black-hsl-1-075-star.tga                                        %target_folder%\black-hsl-1-075-star.tga
%program_TC% %left_folder%\black-hsl-1-100-alvy.tga                           %right_folder%\black-hsl-1-100-alvy.tga                                        %target_folder%\black-hsl-1-100-alvy.tga
%program_TC% %left_folder%\black-hsl-1-100-star.tga                           %right_folder%\black-hsl-1-100-star.tga                                        %target_folder%\black-hsl-1-100-star.tga
%program_TC% %left_folder%\blue-hsl-1-000-channel.tga                         %right_folder%\blue-hsl-1-000-channel.tga                                      %target_folder%\blue-hsl-1-000-channel.tga
%program_TC% %left_folder%\blue-hsl-1-000-star.tga                            %right_folder%\blue-hsl-1-000-star.tga                                         %target_folder%\blue-hsl-1-000-star.tga
%program_TC% %left_folder%\blue-hsl-1-025-channel.tga                         %right_folder%\blue-hsl-1-025-channel.tga                                      %target_folder%\blue-hsl-1-025-channel.tga
%program_TC% %left_folder%\blue-hsl-1-025-star.tga                            %right_folder%\blue-hsl-1-025-star.tga                                         %target_folder%\blue-hsl-1-025-star.tga
%program_TC% %left_folder%\blue-hsl-1-050-channel.tga                         %right_folder%\blue-hsl-1-050-channel.tga                                      %target_folder%\blue-hsl-1-050-channel.tga
%program_TC% %left_folder%\blue-hsl-1-050-star.tga                            %right_folder%\blue-hsl-1-050-star.tga                                         %target_folder%\blue-hsl-1-050-star.tga
%program_TC% %left_folder%\blue-hsl-1-075-channel.tga                         %right_folder%\blue-hsl-1-075-channel.tga                                      %target_folder%\blue-hsl-1-075-channel.tga
%program_TC% %left_folder%\blue-hsl-1-075-star.tga                            %right_folder%\blue-hsl-1-075-star.tga                                         %target_folder%\blue-hsl-1-075-star.tga
%program_TC% %left_folder%\blue-hsl-1-100-channel.tga                         %right_folder%\blue-hsl-1-100-channel.tga                                      %target_folder%\blue-hsl-1-100-channel.tga
%program_TC% %left_folder%\blue-hsl-1-100-star.tga                            %right_folder%\blue-hsl-1-100-star.tga                                         %target_folder%\blue-hsl-1-100-star.tga
%program_TC% %left_folder%\color-aqua-hue-color.tga                           %right_folder%\color-aqua-hue-color.tga                                        %target_folder%\color-aqua-hue-color.tga
%program_TC% %left_folder%\color-aquamarine-hue-color.tga                     %right_folder%\color-aquamarine-hue-color.tga                                  %target_folder%\color-aquamarine-hue-color.tga
%program_TC% %left_folder%\color-azure-hue-color.tga                          %right_folder%\color-azure-hue-color.tga                                       %target_folder%\color-azure-hue-color.tga
%program_TC% %left_folder%\color-beige-hue-color.tga                          %right_folder%\color-beige-hue-color.tga                                       %target_folder%\color-beige-hue-color.tga
%program_TC% %left_folder%\color-bisque-hue-color.tga                         %right_folder%\color-bisque-hue-color.tga                                      %target_folder%\color-bisque-hue-color.tga
%program_TC% %left_folder%\color-blue-hue-color.tga                           %right_folder%\color-blue-hue-color.tga                                        %target_folder%\color-blue-hue-color.tga
%program_TC% %left_folder%\color-gold-hue-color.tga                           %right_folder%\color-gold-hue-color.tga                                        %target_folder%\color-gold-hue-color.tga
%program_TC% %left_folder%\color-gray-hue-color.tga                           %right_folder%\color-gray-hue-color.tga                                        %target_folder%\color-gray-hue-color.tga
%program_TC% %left_folder%\color-lime-hue-color.tga                           %right_folder%\color-lime-hue-color.tga                                        %target_folder%\color-lime-hue-color.tga
%program_TC% %left_folder%\color-magenta-hue-color.tga                        %right_folder%\color-magenta-hue-color.tga                                     %target_folder%\color-magenta-hue-color.tga
%program_TC% %left_folder%\color-red-hue-color.tga                            %right_folder%\color-red-hue-color.tga                                         %target_folder%\color-red-hue-color.tga
%program_TC% %left_folder%\cyan-hsl-1-000-cmy.tga                             %right_folder%\cyan-hsl-1-000-cmy.tga                                          %target_folder%\cyan-hsl-1-000-cmy.tga
%program_TC% %left_folder%\cyan-hsl-1-000-cmyk.tga                            %right_folder%\cyan-hsl-1-000-cmyk.tga                                         %target_folder%\cyan-hsl-1-000-cmyk.tga
%program_TC% %left_folder%\cyan-hsl-1-000-star.tga                            %right_folder%\cyan-hsl-1-000-star.tga                                         %target_folder%\cyan-hsl-1-000-star.tga
%program_TC% %left_folder%\cyan-hsl-1-025-cmy.tga                             %right_folder%\cyan-hsl-1-025-cmy.tga                                          %target_folder%\cyan-hsl-1-025-cmy.tga
%program_TC% %left_folder%\cyan-hsl-1-025-cmyk.tga                            %right_folder%\cyan-hsl-1-025-cmyk.tga                                         %target_folder%\cyan-hsl-1-025-cmyk.tga
%program_TC% %left_folder%\cyan-hsl-1-025-star.tga                            %right_folder%\cyan-hsl-1-025-star.tga                                         %target_folder%\cyan-hsl-1-025-star.tga
%program_TC% %left_folder%\cyan-hsl-1-050-cmy.tga                             %right_folder%\cyan-hsl-1-050-cmy.tga                                          %target_folder%\cyan-hsl-1-050-cmy.tga
%program_TC% %left_folder%\cyan-hsl-1-050-cmyk.tga                            %right_folder%\cyan-hsl-1-050-cmyk.tga                                         %target_folder%\cyan-hsl-1-050-cmyk.tga
%program_TC% %left_folder%\cyan-hsl-1-050-star.tga                            %right_folder%\cyan-hsl-1-050-star.tga                                         %target_folder%\cyan-hsl-1-050-star.tga
%program_TC% %left_folder%\cyan-hsl-1-075-cmy.tga                             %right_folder%\cyan-hsl-1-075-cmy.tga                                          %target_folder%\cyan-hsl-1-075-cmy.tga
%program_TC% %left_folder%\cyan-hsl-1-075-cmyk.tga                            %right_folder%\cyan-hsl-1-075-cmyk.tga                                         %target_folder%\cyan-hsl-1-075-cmyk.tga
%program_TC% %left_folder%\cyan-hsl-1-075-star.tga                            %right_folder%\cyan-hsl-1-075-star.tga                                         %target_folder%\cyan-hsl-1-075-star.tga
%program_TC% %left_folder%\cyan-hsl-1-100-cmy.tga                             %right_folder%\cyan-hsl-1-100-cmy.tga                                          %target_folder%\cyan-hsl-1-100-cmy.tga
%program_TC% %left_folder%\cyan-hsl-1-100-cmyk.tga                            %right_folder%\cyan-hsl-1-100-cmyk.tga                                         %target_folder%\cyan-hsl-1-100-cmyk.tga
%program_TC% %left_folder%\cyan-hsl-1-100-star.tga                            %right_folder%\cyan-hsl-1-100-star.tga                                         %target_folder%\cyan-hsl-1-100-star.tga
%program_TC% %left_folder%\gray-hsl-1-000-average.tga                         %right_folder%\gray-hsl-1-000-average.tga                                      %target_folder%\gray-hsl-1-000-average.tga
%program_TC% %left_folder%\gray-hsl-1-000-lightness.tga                       %right_folder%\gray-hsl-1-000-lightness.tga                                    %target_folder%\gray-hsl-1-000-lightness.tga
%program_TC% %left_folder%\gray-hsl-1-000-middle.tga                          %right_folder%\gray-hsl-1-000-middle.tga                                       %target_folder%\gray-hsl-1-000-middle.tga
%program_TC% %left_folder%\gray-hsl-1-000-star.tga                            %right_folder%\gray-hsl-1-000-star.tga                                         %target_folder%\gray-hsl-1-000-star.tga
%program_TC% %left_folder%\gray-hsl-1-000-yuv709.tga                          %right_folder%\gray-hsl-1-000-yuv709.tga                                       %target_folder%\gray-hsl-1-000-yuv709.tga
%program_TC% %left_folder%\gray-hsl-1-025-average.tga                         %right_folder%\gray-hsl-1-025-average.tga                                      %target_folder%\gray-hsl-1-025-average.tga
%program_TC% %left_folder%\gray-hsl-1-025-lightness.tga                       %right_folder%\gray-hsl-1-025-lightness.tga                                    %target_folder%\gray-hsl-1-025-lightness.tga
%program_TC% %left_folder%\gray-hsl-1-025-middle.tga                          %right_folder%\gray-hsl-1-025-middle.tga                                       %target_folder%\gray-hsl-1-025-middle.tga
%program_TC% %left_folder%\gray-hsl-1-025-star.tga                            %right_folder%\gray-hsl-1-025-star.tga                                         %target_folder%\gray-hsl-1-025-star.tga
%program_TC% %left_folder%\gray-hsl-1-025-yuv709.tga                          %right_folder%\gray-hsl-1-025-yuv709.tga                                       %target_folder%\gray-hsl-1-025-yuv709.tga
%program_TC% %left_folder%\gray-hsl-1-050-average.tga                         %right_folder%\gray-hsl-1-050-average.tga                                      %target_folder%\gray-hsl-1-050-average.tga
%program_TC% %left_folder%\gray-hsl-1-050-lightness.tga                       %right_folder%\gray-hsl-1-050-lightness.tga                                    %target_folder%\gray-hsl-1-050-lightness.tga
%program_TC% %left_folder%\gray-hsl-1-050-middle.tga                          %right_folder%\gray-hsl-1-050-middle.tga                                       %target_folder%\gray-hsl-1-050-middle.tga
%program_TC% %left_folder%\gray-hsl-1-050-star.tga                            %right_folder%\gray-hsl-1-050-star.tga                                         %target_folder%\gray-hsl-1-050-star.tga
%program_TC% %left_folder%\gray-hsl-1-050-yuv709.tga                          %right_folder%\gray-hsl-1-050-yuv709.tga                                       %target_folder%\gray-hsl-1-050-yuv709.tga
%program_TC% %left_folder%\gray-hsl-1-075-average.tga                         %right_folder%\gray-hsl-1-075-average.tga                                      %target_folder%\gray-hsl-1-075-average.tga
%program_TC% %left_folder%\gray-hsl-1-075-lightness.tga                       %right_folder%\gray-hsl-1-075-lightness.tga                                    %target_folder%\gray-hsl-1-075-lightness.tga
%program_TC% %left_folder%\gray-hsl-1-075-middle.tga                          %right_folder%\gray-hsl-1-075-middle.tga                                       %target_folder%\gray-hsl-1-075-middle.tga
%program_TC% %left_folder%\gray-hsl-1-075-star.tga                            %right_folder%\gray-hsl-1-075-star.tga                                         %target_folder%\gray-hsl-1-075-star.tga
%program_TC% %left_folder%\gray-hsl-1-075-yuv709.tga                          %right_folder%\gray-hsl-1-075-yuv709.tga                                       %target_folder%\gray-hsl-1-075-yuv709.tga
%program_TC% %left_folder%\gray-hsl-1-100-average.tga                         %right_folder%\gray-hsl-1-100-average.tga                                      %target_folder%\gray-hsl-1-100-average.tga
%program_TC% %left_folder%\gray-hsl-1-100-lightness.tga                       %right_folder%\gray-hsl-1-100-lightness.tga                                    %target_folder%\gray-hsl-1-100-lightness.tga
%program_TC% %left_folder%\gray-hsl-1-100-middle.tga                          %right_folder%\gray-hsl-1-100-middle.tga                                       %target_folder%\gray-hsl-1-100-middle.tga
%program_TC% %left_folder%\gray-hsl-1-100-star.tga                            %right_folder%\gray-hsl-1-100-star.tga                                         %target_folder%\gray-hsl-1-100-star.tga
%program_TC% %left_folder%\gray-hsl-1-100-yuv709.tga                          %right_folder%\gray-hsl-1-100-yuv709.tga                                       %target_folder%\gray-hsl-1-100-yuv709.tga
%program_TC% %left_folder%\green-hsl-1-000-channel.tga                        %right_folder%\green-hsl-1-000-channel.tga                                     %target_folder%\green-hsl-1-000-channel.tga
%program_TC% %left_folder%\green-hsl-1-000-star.tga                           %right_folder%\green-hsl-1-000-star.tga                                        %target_folder%\green-hsl-1-000-star.tga
%program_TC% %left_folder%\green-hsl-1-025-channel.tga                        %right_folder%\green-hsl-1-025-channel.tga                                     %target_folder%\green-hsl-1-025-channel.tga
%program_TC% %left_folder%\green-hsl-1-025-star.tga                           %right_folder%\green-hsl-1-025-star.tga                                        %target_folder%\green-hsl-1-025-star.tga
%program_TC% %left_folder%\green-hsl-1-050-channel.tga                        %right_folder%\green-hsl-1-050-channel.tga                                     %target_folder%\green-hsl-1-050-channel.tga
%program_TC% %left_folder%\green-hsl-1-050-star.tga                           %right_folder%\green-hsl-1-050-star.tga                                        %target_folder%\green-hsl-1-050-star.tga
%program_TC% %left_folder%\green-hsl-1-075-channel.tga                        %right_folder%\green-hsl-1-075-channel.tga                                     %target_folder%\green-hsl-1-075-channel.tga
%program_TC% %left_folder%\green-hsl-1-075-star.tga                           %right_folder%\green-hsl-1-075-star.tga                                        %target_folder%\green-hsl-1-075-star.tga
%program_TC% %left_folder%\green-hsl-1-100-channel.tga                        %right_folder%\green-hsl-1-100-channel.tga                                     %target_folder%\green-hsl-1-100-channel.tga
%program_TC% %left_folder%\green-hsl-1-100-star.tga                           %right_folder%\green-hsl-1-100-star.tga                                        %target_folder%\green-hsl-1-100-star.tga
%program_TC% %left_folder%\magenta-hsl-1-000-cmy.tga                          %right_folder%\magenta-hsl-1-000-cmy.tga                                       %target_folder%\magenta-hsl-1-000-cmy.tga
%program_TC% %left_folder%\magenta-hsl-1-000-cmyk.tga                         %right_folder%\magenta-hsl-1-000-cmyk.tga                                      %target_folder%\magenta-hsl-1-000-cmyk.tga
%program_TC% %left_folder%\magenta-hsl-1-000-star.tga                         %right_folder%\magenta-hsl-1-000-star.tga                                      %target_folder%\magenta-hsl-1-000-star.tga
%program_TC% %left_folder%\magenta-hsl-1-025-cmy.tga                          %right_folder%\magenta-hsl-1-025-cmy.tga                                       %target_folder%\magenta-hsl-1-025-cmy.tga
%program_TC% %left_folder%\magenta-hsl-1-025-cmyk.tga                         %right_folder%\magenta-hsl-1-025-cmyk.tga                                      %target_folder%\magenta-hsl-1-025-cmyk.tga
%program_TC% %left_folder%\magenta-hsl-1-025-star.tga                         %right_folder%\magenta-hsl-1-025-star.tga                                      %target_folder%\magenta-hsl-1-025-star.tga
%program_TC% %left_folder%\magenta-hsl-1-050-cmy.tga                          %right_folder%\magenta-hsl-1-050-cmy.tga                                       %target_folder%\magenta-hsl-1-050-cmy.tga
%program_TC% %left_folder%\magenta-hsl-1-050-cmyk.tga                         %right_folder%\magenta-hsl-1-050-cmyk.tga                                      %target_folder%\magenta-hsl-1-050-cmyk.tga
%program_TC% %left_folder%\magenta-hsl-1-050-star.tga                         %right_folder%\magenta-hsl-1-050-star.tga                                      %target_folder%\magenta-hsl-1-050-star.tga
%program_TC% %left_folder%\magenta-hsl-1-075-cmy.tga                          %right_folder%\magenta-hsl-1-075-cmy.tga                                       %target_folder%\magenta-hsl-1-075-cmy.tga
%program_TC% %left_folder%\magenta-hsl-1-075-cmyk.tga                         %right_folder%\magenta-hsl-1-075-cmyk.tga                                      %target_folder%\magenta-hsl-1-075-cmyk.tga
%program_TC% %left_folder%\magenta-hsl-1-075-star.tga                         %right_folder%\magenta-hsl-1-075-star.tga                                      %target_folder%\magenta-hsl-1-075-star.tga
%program_TC% %left_folder%\magenta-hsl-1-100-cmy.tga                          %right_folder%\magenta-hsl-1-100-cmy.tga                                       %target_folder%\magenta-hsl-1-100-cmy.tga
%program_TC% %left_folder%\magenta-hsl-1-100-cmyk.tga                         %right_folder%\magenta-hsl-1-100-cmyk.tga                                      %target_folder%\magenta-hsl-1-100-cmyk.tga
%program_TC% %left_folder%\magenta-hsl-1-100-star.tga                         %right_folder%\magenta-hsl-1-100-star.tga                                      %target_folder%\magenta-hsl-1-100-star.tga
%program_TC% %left_folder%\red-hsl-1-000-channel.tga                          %right_folder%\red-hsl-1-000-channel.tga                                       %target_folder%\red-hsl-1-000-channel.tga
%program_TC% %left_folder%\red-hsl-1-000-star.tga                             %right_folder%\red-hsl-1-000-star.tga                                          %target_folder%\red-hsl-1-000-star.tga
%program_TC% %left_folder%\red-hsl-1-025-channel.tga                          %right_folder%\red-hsl-1-025-channel.tga                                       %target_folder%\red-hsl-1-025-channel.tga
%program_TC% %left_folder%\red-hsl-1-025-star.tga                             %right_folder%\red-hsl-1-025-star.tga                                          %target_folder%\red-hsl-1-025-star.tga
%program_TC% %left_folder%\red-hsl-1-050-channel.tga                          %right_folder%\red-hsl-1-050-channel.tga                                       %target_folder%\red-hsl-1-050-channel.tga
%program_TC% %left_folder%\red-hsl-1-050-star.tga                             %right_folder%\red-hsl-1-050-star.tga                                          %target_folder%\red-hsl-1-050-star.tga
%program_TC% %left_folder%\red-hsl-1-075-channel.tga                          %right_folder%\red-hsl-1-075-channel.tga                                       %target_folder%\red-hsl-1-075-channel.tga
%program_TC% %left_folder%\red-hsl-1-075-star.tga                             %right_folder%\red-hsl-1-075-star.tga                                          %target_folder%\red-hsl-1-075-star.tga
%program_TC% %left_folder%\red-hsl-1-100-channel.tga                          %right_folder%\red-hsl-1-100-channel.tga                                       %target_folder%\red-hsl-1-100-channel.tga
%program_TC% %left_folder%\red-hsl-1-100-star.tga                             %right_folder%\red-hsl-1-100-star.tga                                          %target_folder%\red-hsl-1-100-star.tga
%program_TC% %left_folder%\saturation-hsl-1-000-hsi-ref.tga                   %right_folder%\saturation-hsl-1-000-hsi-ref.tga                                %target_folder%\saturation-hsl-1-000-hsi-ref.tga
%program_TC% %left_folder%\saturation-hsl-1-000-hsi-rgb.tga                   %right_folder%\saturation-hsl-1-000-hsi-rgb.tga                                %target_folder%\saturation-hsl-1-000-hsi-rgb.tga
%program_TC% %left_folder%\saturation-hsl-1-000-hsl-ref.tga                   %right_folder%\saturation-hsl-1-000-hsl-ref.tga                                %target_folder%\saturation-hsl-1-000-hsl-ref.tga
%program_TC% %left_folder%\saturation-hsl-1-000-hsl-rgb.tga                   %right_folder%\saturation-hsl-1-000-hsl-rgb.tga                                %target_folder%\saturation-hsl-1-000-hsl-rgb.tga
%program_TC% %left_folder%\saturation-hsl-1-000-hsv-ref.tga                   %right_folder%\saturation-hsl-1-000-hsv-ref.tga                                %target_folder%\saturation-hsl-1-000-hsv-ref.tga
%program_TC% %left_folder%\saturation-hsl-1-000-hsv-rgb.tga                   %right_folder%\saturation-hsl-1-000-hsv-rgb.tga                                %target_folder%\saturation-hsl-1-000-hsv-rgb.tga
%program_TC% %left_folder%\saturation-hsl-1-000-lab.tga                       %right_folder%\saturation-hsl-1-000-lab.tga                                    %target_folder%\saturation-hsl-1-000-lab.tga
%program_TC% %left_folder%\saturation-hsl-1-000-LabCH.tga                     %right_folder%\saturation-hsl-1-000-LabCH.tga                                  %target_folder%\saturation-hsl-1-000-LabCH.tga
%program_TC% %left_folder%\saturation-hsl-1-000-luv.tga                       %right_folder%\saturation-hsl-1-000-luv.tga                                    %target_folder%\saturation-hsl-1-000-luv.tga
%program_TC% %left_folder%\saturation-hsl-1-025-hsi-ref.tga                   %right_folder%\saturation-hsl-1-025-hsi-ref.tga                                %target_folder%\saturation-hsl-1-025-hsi-ref.tga
%program_TC% %left_folder%\saturation-hsl-1-025-hsi-rgb.tga                   %right_folder%\saturation-hsl-1-025-hsi-rgb.tga                                %target_folder%\saturation-hsl-1-025-hsi-rgb.tga
%program_TC% %left_folder%\saturation-hsl-1-025-hsl-ref.tga                   %right_folder%\saturation-hsl-1-025-hsl-ref.tga                                %target_folder%\saturation-hsl-1-025-hsl-ref.tga
%program_TC% %left_folder%\saturation-hsl-1-025-hsl-rgb.tga                   %right_folder%\saturation-hsl-1-025-hsl-rgb.tga                                %target_folder%\saturation-hsl-1-025-hsl-rgb.tga
%program_TC% %left_folder%\saturation-hsl-1-025-hsv-ref.tga                   %right_folder%\saturation-hsl-1-025-hsv-ref.tga                                %target_folder%\saturation-hsl-1-025-hsv-ref.tga
%program_TC% %left_folder%\saturation-hsl-1-025-hsv-rgb.tga                   %right_folder%\saturation-hsl-1-025-hsv-rgb.tga                                %target_folder%\saturation-hsl-1-025-hsv-rgb.tga
%program_TC% %left_folder%\saturation-hsl-1-025-lab.tga                       %right_folder%\saturation-hsl-1-025-lab.tga                                    %target_folder%\saturation-hsl-1-025-lab.tga
%program_TC% %left_folder%\saturation-hsl-1-025-LabCH.tga                     %right_folder%\saturation-hsl-1-025-LabCH.tga                                  %target_folder%\saturation-hsl-1-025-LabCH.tga
%program_TC% %left_folder%\saturation-hsl-1-025-luv.tga                       %right_folder%\saturation-hsl-1-025-luv.tga                                    %target_folder%\saturation-hsl-1-025-luv.tga
%program_TC% %left_folder%\saturation-hsl-1-050-hsi-ref.tga                   %right_folder%\saturation-hsl-1-050-hsi-ref.tga                                %target_folder%\saturation-hsl-1-050-hsi-ref.tga
%program_TC% %left_folder%\saturation-hsl-1-050-hsi-rgb.tga                   %right_folder%\saturation-hsl-1-050-hsi-rgb.tga                                %target_folder%\saturation-hsl-1-050-hsi-rgb.tga
%program_TC% %left_folder%\saturation-hsl-1-050-hsl-ref.tga                   %right_folder%\saturation-hsl-1-050-hsl-ref.tga                                %target_folder%\saturation-hsl-1-050-hsl-ref.tga
%program_TC% %left_folder%\saturation-hsl-1-050-hsl-rgb.tga                   %right_folder%\saturation-hsl-1-050-hsl-rgb.tga                                %target_folder%\saturation-hsl-1-050-hsl-rgb.tga
%program_TC% %left_folder%\saturation-hsl-1-050-hsv-ref.tga                   %right_folder%\saturation-hsl-1-050-hsv-ref.tga                                %target_folder%\saturation-hsl-1-050-hsv-ref.tga
%program_TC% %left_folder%\saturation-hsl-1-050-hsv-rgb.tga                   %right_folder%\saturation-hsl-1-050-hsv-rgb.tga                                %target_folder%\saturation-hsl-1-050-hsv-rgb.tga
%program_TC% %left_folder%\saturation-hsl-1-050-lab.tga                       %right_folder%\saturation-hsl-1-050-lab.tga                                    %target_folder%\saturation-hsl-1-050-lab.tga
%program_TC% %left_folder%\saturation-hsl-1-050-LabCH.tga                     %right_folder%\saturation-hsl-1-050-LabCH.tga                                  %target_folder%\saturation-hsl-1-050-LabCH.tga
%program_TC% %left_folder%\saturation-hsl-1-050-luv.tga                       %right_folder%\saturation-hsl-1-050-luv.tga                                    %target_folder%\saturation-hsl-1-050-luv.tga
%program_TC% %left_folder%\saturation-hsl-1-075-hsi-ref.tga                   %right_folder%\saturation-hsl-1-075-hsi-ref.tga                                %target_folder%\saturation-hsl-1-075-hsi-ref.tga
%program_TC% %left_folder%\saturation-hsl-1-075-hsi-rgb.tga                   %right_folder%\saturation-hsl-1-075-hsi-rgb.tga                                %target_folder%\saturation-hsl-1-075-hsi-rgb.tga
%program_TC% %left_folder%\saturation-hsl-1-075-hsl-ref.tga                   %right_folder%\saturation-hsl-1-075-hsl-ref.tga                                %target_folder%\saturation-hsl-1-075-hsl-ref.tga
%program_TC% %left_folder%\saturation-hsl-1-075-hsl-rgb.tga                   %right_folder%\saturation-hsl-1-075-hsl-rgb.tga                                %target_folder%\saturation-hsl-1-075-hsl-rgb.tga
%program_TC% %left_folder%\saturation-hsl-1-075-hsv-ref.tga                   %right_folder%\saturation-hsl-1-075-hsv-ref.tga                                %target_folder%\saturation-hsl-1-075-hsv-ref.tga
%program_TC% %left_folder%\saturation-hsl-1-075-hsv-rgb.tga                   %right_folder%\saturation-hsl-1-075-hsv-rgb.tga                                %target_folder%\saturation-hsl-1-075-hsv-rgb.tga
%program_TC% %left_folder%\saturation-hsl-1-075-lab.tga                       %right_folder%\saturation-hsl-1-075-lab.tga                                    %target_folder%\saturation-hsl-1-075-lab.tga
%program_TC% %left_folder%\saturation-hsl-1-075-LabCH.tga                     %right_folder%\saturation-hsl-1-075-LabCH.tga                                  %target_folder%\saturation-hsl-1-075-LabCH.tga
%program_TC% %left_folder%\saturation-hsl-1-075-luv.tga                       %right_folder%\saturation-hsl-1-075-luv.tga                                    %target_folder%\saturation-hsl-1-075-luv.tga
%program_TC% %left_folder%\saturation-hsl-1-100-hsi-ref.tga                   %right_folder%\saturation-hsl-1-100-hsi-ref.tga                                %target_folder%\saturation-hsl-1-100-hsi-ref.tga
%program_TC% %left_folder%\saturation-hsl-1-100-hsi-rgb.tga                   %right_folder%\saturation-hsl-1-100-hsi-rgb.tga                                %target_folder%\saturation-hsl-1-100-hsi-rgb.tga
%program_TC% %left_folder%\saturation-hsl-1-100-hsl-ref.tga                   %right_folder%\saturation-hsl-1-100-hsl-ref.tga                                %target_folder%\saturation-hsl-1-100-hsl-ref.tga
%program_TC% %left_folder%\saturation-hsl-1-100-hsl-rgb.tga                   %right_folder%\saturation-hsl-1-100-hsl-rgb.tga                                %target_folder%\saturation-hsl-1-100-hsl-rgb.tga
%program_TC% %left_folder%\saturation-hsl-1-100-hsv-ref.tga                   %right_folder%\saturation-hsl-1-100-hsv-ref.tga                                %target_folder%\saturation-hsl-1-100-hsv-ref.tga
%program_TC% %left_folder%\saturation-hsl-1-100-hsv-rgb.tga                   %right_folder%\saturation-hsl-1-100-hsv-rgb.tga                                %target_folder%\saturation-hsl-1-100-hsv-rgb.tga
%program_TC% %left_folder%\saturation-hsl-1-100-lab.tga                       %right_folder%\saturation-hsl-1-100-lab.tga                                    %target_folder%\saturation-hsl-1-100-lab.tga
%program_TC% %left_folder%\saturation-hsl-1-100-LabCH.tga                     %right_folder%\saturation-hsl-1-100-LabCH.tga                                  %target_folder%\saturation-hsl-1-100-LabCH.tga
%program_TC% %left_folder%\saturation-hsl-1-100-luv.tga                       %right_folder%\saturation-hsl-1-100-luv.tga                                    %target_folder%\saturation-hsl-1-100-luv.tga
%program_TC% %left_folder%\white-hsl-1-000-alvy.tga                           %right_folder%\white-hsl-1-000-alvy.tga                                        %target_folder%\white-hsl-1-000-alvy.tga
%program_TC% %left_folder%\white-hsl-1-000-star.tga                           %right_folder%\white-hsl-1-000-star.tga                                        %target_folder%\white-hsl-1-000-star.tga
%program_TC% %left_folder%\white-hsl-1-025-alvy.tga                           %right_folder%\white-hsl-1-025-alvy.tga                                        %target_folder%\white-hsl-1-025-alvy.tga
%program_TC% %left_folder%\white-hsl-1-025-star.tga                           %right_folder%\white-hsl-1-025-star.tga                                        %target_folder%\white-hsl-1-025-star.tga
%program_TC% %left_folder%\white-hsl-1-050-alvy.tga                           %right_folder%\white-hsl-1-050-alvy.tga                                        %target_folder%\white-hsl-1-050-alvy.tga
%program_TC% %left_folder%\white-hsl-1-050-star.tga                           %right_folder%\white-hsl-1-050-star.tga                                        %target_folder%\white-hsl-1-050-star.tga
%program_TC% %left_folder%\white-hsl-1-075-alvy.tga                           %right_folder%\white-hsl-1-075-alvy.tga                                        %target_folder%\white-hsl-1-075-alvy.tga
%program_TC% %left_folder%\white-hsl-1-075-star.tga                           %right_folder%\white-hsl-1-075-star.tga                                        %target_folder%\white-hsl-1-075-star.tga
%program_TC% %left_folder%\white-hsl-1-100-alvy.tga                           %right_folder%\white-hsl-1-100-alvy.tga                                        %target_folder%\white-hsl-1-100-alvy.tga
%program_TC% %left_folder%\white-hsl-1-100-star.tga                           %right_folder%\white-hsl-1-100-star.tga                                        %target_folder%\white-hsl-1-100-star.tga
%program_TC% %left_folder%\yellow-hsl-1-000-cmy.tga                           %right_folder%\yellow-hsl-1-000-cmy.tga                                        %target_folder%\yellow-hsl-1-000-cmy.tga
%program_TC% %left_folder%\yellow-hsl-1-000-cmyk.tga                          %right_folder%\yellow-hsl-1-000-cmyk.tga                                       %target_folder%\yellow-hsl-1-000-cmyk.tga
%program_TC% %left_folder%\yellow-hsl-1-000-star.tga                          %right_folder%\yellow-hsl-1-000-star.tga                                       %target_folder%\yellow-hsl-1-000-star.tga
%program_TC% %left_folder%\yellow-hsl-1-025-cmy.tga                           %right_folder%\yellow-hsl-1-025-cmy.tga                                        %target_folder%\yellow-hsl-1-025-cmy.tga
%program_TC% %left_folder%\yellow-hsl-1-025-cmyk.tga                          %right_folder%\yellow-hsl-1-025-cmyk.tga                                       %target_folder%\yellow-hsl-1-025-cmyk.tga
%program_TC% %left_folder%\yellow-hsl-1-025-star.tga                          %right_folder%\yellow-hsl-1-025-star.tga                                       %target_folder%\yellow-hsl-1-025-star.tga
%program_TC% %left_folder%\yellow-hsl-1-050-cmy.tga                           %right_folder%\yellow-hsl-1-050-cmy.tga                                        %target_folder%\yellow-hsl-1-050-cmy.tga
%program_TC% %left_folder%\yellow-hsl-1-050-cmyk.tga                          %right_folder%\yellow-hsl-1-050-cmyk.tga                                       %target_folder%\yellow-hsl-1-050-cmyk.tga
%program_TC% %left_folder%\yellow-hsl-1-050-star.tga                          %right_folder%\yellow-hsl-1-050-star.tga                                       %target_folder%\yellow-hsl-1-050-star.tga
%program_TC% %left_folder%\yellow-hsl-1-075-cmy.tga                           %right_folder%\yellow-hsl-1-075-cmy.tga                                        %target_folder%\yellow-hsl-1-075-cmy.tga
%program_TC% %left_folder%\yellow-hsl-1-075-cmyk.tga                          %right_folder%\yellow-hsl-1-075-cmyk.tga                                       %target_folder%\yellow-hsl-1-075-cmyk.tga
%program_TC% %left_folder%\yellow-hsl-1-075-star.tga                          %right_folder%\yellow-hsl-1-075-star.tga                                       %target_folder%\yellow-hsl-1-075-star.tga
%program_TC% %left_folder%\yellow-hsl-1-100-cmy.tga                           %right_folder%\yellow-hsl-1-100-cmy.tga                                        %target_folder%\yellow-hsl-1-100-cmy.tga
%program_TC% %left_folder%\yellow-hsl-1-100-cmyk.tga                          %right_folder%\yellow-hsl-1-100-cmyk.tga                                       %target_folder%\yellow-hsl-1-100-cmyk.tga
%program_TC% %left_folder%\yellow-hsl-1-100-star.tga                          %right_folder%\yellow-hsl-1-100-star.tga                                       %target_folder%\yellow-hsl-1-100-star.tga

pause