echo off

set  program_TC=..\out\tc.exe
set  left_folder=..\out\conv-rgb
set  right_folder=..\out\conv
set  target_folder=..\out\check

%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2bgr.tga                         %target_folder%\bgr2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2cmy.tga                         %target_folder%\bgr2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2cmyk.tga                        %target_folder%\bgr2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2hsi.tga                         %target_folder%\bgr2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2hsl.tga                         %target_folder%\bgr2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2hsv.tga                         %target_folder%\bgr2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2hwb.tga                         %target_folder%\bgr2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2LabCH.tga                       %target_folder%\bgr2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2labCIE.tga                      %target_folder%\bgr2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2labHunter.tga                   %target_folder%\bgr2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2lms.tga                         %target_folder%\bgr2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2luv.tga                         %target_folder%\bgr2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2LuvCH.tga                       %target_folder%\bgr2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2rgb.tga                         %target_folder%\bgr2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2xyy.tga                         %target_folder%\bgr2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2xyz.tga                         %target_folder%\bgr2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2YCgCo.tga                       %target_folder%\bgr2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2YDbDr.tga                       %target_folder%\bgr2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2yiq.tga                         %target_folder%\bgr2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2YPbPr709.tga                    %target_folder%\bgr2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2yuv601.tga                      %target_folder%\bgr2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\bgr2yuv709.tga                      %target_folder%\bgr2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2bgr.tga                         %target_folder%\cmy2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2cmy.tga                         %target_folder%\cmy2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2cmyk.tga                        %target_folder%\cmy2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2hsi.tga                         %target_folder%\cmy2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2hsl.tga                         %target_folder%\cmy2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2hsv.tga                         %target_folder%\cmy2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2hwb.tga                         %target_folder%\cmy2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2LabCH.tga                       %target_folder%\cmy2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2labCIE.tga                      %target_folder%\cmy2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2labHunter.tga                   %target_folder%\cmy2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2lms.tga                         %target_folder%\cmy2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2luv.tga                         %target_folder%\cmy2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2LuvCH.tga                       %target_folder%\cmy2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2rgb.tga                         %target_folder%\cmy2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2xyy.tga                         %target_folder%\cmy2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2xyz.tga                         %target_folder%\cmy2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2YCgCo.tga                       %target_folder%\cmy2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2YDbDr.tga                       %target_folder%\cmy2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2yiq.tga                         %target_folder%\cmy2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2YPbPr709.tga                    %target_folder%\cmy2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2yuv601.tga                      %target_folder%\cmy2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmy2yuv709.tga                      %target_folder%\cmy2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2bgr.tga                        %target_folder%\cmyk2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2cmy.tga                        %target_folder%\cmyk2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2cmyk.tga                       %target_folder%\cmyk2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2hsi.tga                        %target_folder%\cmyk2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2hsl.tga                        %target_folder%\cmyk2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2hsv.tga                        %target_folder%\cmyk2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2hwb.tga                        %target_folder%\cmyk2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2LabCH.tga                      %target_folder%\cmyk2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2labCIE.tga                     %target_folder%\cmyk2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2labHunter.tga                  %target_folder%\cmyk2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2lms.tga                        %target_folder%\cmyk2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2luv.tga                        %target_folder%\cmyk2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2LuvCH.tga                      %target_folder%\cmyk2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2rgb.tga                        %target_folder%\cmyk2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2xyy.tga                        %target_folder%\cmyk2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2xyz.tga                        %target_folder%\cmyk2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2YCgCo.tga                      %target_folder%\cmyk2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2YDbDr.tga                      %target_folder%\cmyk2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2yiq.tga                        %target_folder%\cmyk2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2YPbPr709.tga                   %target_folder%\cmyk2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2yuv601.tga                     %target_folder%\cmyk2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\cmyk2yuv709.tga                     %target_folder%\cmyk2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2bgr.tga                         %target_folder%\hsi2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2cmy.tga                         %target_folder%\hsi2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2cmyk.tga                        %target_folder%\hsi2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2hsi.tga                         %target_folder%\hsi2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2hsl.tga                         %target_folder%\hsi2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2hsv.tga                         %target_folder%\hsi2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2hwb.tga                         %target_folder%\hsi2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2LabCH.tga                       %target_folder%\hsi2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2labCIE.tga                      %target_folder%\hsi2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2labHunter.tga                   %target_folder%\hsi2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2lms.tga                         %target_folder%\hsi2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2luv.tga                         %target_folder%\hsi2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2LuvCH.tga                       %target_folder%\hsi2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2rgb.tga                         %target_folder%\hsi2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2xyy.tga                         %target_folder%\hsi2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2xyz.tga                         %target_folder%\hsi2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2YCgCo.tga                       %target_folder%\hsi2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2YDbDr.tga                       %target_folder%\hsi2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2yiq.tga                         %target_folder%\hsi2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2YPbPr709.tga                    %target_folder%\hsi2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2yuv601.tga                      %target_folder%\hsi2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsi2yuv709.tga                      %target_folder%\hsi2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2bgr.tga                         %target_folder%\hsl2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2cmy.tga                         %target_folder%\hsl2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2cmyk.tga                        %target_folder%\hsl2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2hsi.tga                         %target_folder%\hsl2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2hsl.tga                         %target_folder%\hsl2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2hsv.tga                         %target_folder%\hsl2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2hwb.tga                         %target_folder%\hsl2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2LabCH.tga                       %target_folder%\hsl2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2labCIE.tga                      %target_folder%\hsl2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2labHunter.tga                   %target_folder%\hsl2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2lms.tga                         %target_folder%\hsl2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2luv.tga                         %target_folder%\hsl2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2LuvCH.tga                       %target_folder%\hsl2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2rgb.tga                         %target_folder%\hsl2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2xyy.tga                         %target_folder%\hsl2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2xyz.tga                         %target_folder%\hsl2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2YCgCo.tga                       %target_folder%\hsl2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2YDbDr.tga                       %target_folder%\hsl2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2yiq.tga                         %target_folder%\hsl2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2YPbPr709.tga                    %target_folder%\hsl2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2yuv601.tga                      %target_folder%\hsl2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsl2yuv709.tga                      %target_folder%\hsl2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2bgr.tga                         %target_folder%\hsv2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2cmy.tga                         %target_folder%\hsv2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2cmyk.tga                        %target_folder%\hsv2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2hsi.tga                         %target_folder%\hsv2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2hsl.tga                         %target_folder%\hsv2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2hsv.tga                         %target_folder%\hsv2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2hwb.tga                         %target_folder%\hsv2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2LabCH.tga                       %target_folder%\hsv2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2labCIE.tga                      %target_folder%\hsv2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2labHunter.tga                   %target_folder%\hsv2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2lms.tga                         %target_folder%\hsv2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2luv.tga                         %target_folder%\hsv2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2LuvCH.tga                       %target_folder%\hsv2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2rgb.tga                         %target_folder%\hsv2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2xyy.tga                         %target_folder%\hsv2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2xyz.tga                         %target_folder%\hsv2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2YCgCo.tga                       %target_folder%\hsv2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2YDbDr.tga                       %target_folder%\hsv2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2yiq.tga                         %target_folder%\hsv2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2YPbPr709.tga                    %target_folder%\hsv2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2yuv601.tga                      %target_folder%\hsv2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hsv2yuv709.tga                      %target_folder%\hsv2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2bgr.tga                         %target_folder%\hwb2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2cmy.tga                         %target_folder%\hwb2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2cmyk.tga                        %target_folder%\hwb2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2hsi.tga                         %target_folder%\hwb2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2hsl.tga                         %target_folder%\hwb2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2hsv.tga                         %target_folder%\hwb2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2hwb.tga                         %target_folder%\hwb2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2LabCH.tga                       %target_folder%\hwb2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2labCIE.tga                      %target_folder%\hwb2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2labHunter.tga                   %target_folder%\hwb2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2lms.tga                         %target_folder%\hwb2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2luv.tga                         %target_folder%\hwb2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2LuvCH.tga                       %target_folder%\hwb2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2rgb.tga                         %target_folder%\hwb2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2xyy.tga                         %target_folder%\hwb2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2xyz.tga                         %target_folder%\hwb2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2YCgCo.tga                       %target_folder%\hwb2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2YDbDr.tga                       %target_folder%\hwb2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2yiq.tga                         %target_folder%\hwb2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2YPbPr709.tga                    %target_folder%\hwb2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2yuv601.tga                      %target_folder%\hwb2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\hwb2yuv709.tga                      %target_folder%\hwb2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2bgr.tga                       %target_folder%\LabCH2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2cmy.tga                       %target_folder%\LabCH2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2cmyk.tga                      %target_folder%\LabCH2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2hsi.tga                       %target_folder%\LabCH2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2hsl.tga                       %target_folder%\LabCH2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2hsv.tga                       %target_folder%\LabCH2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2hwb.tga                       %target_folder%\LabCH2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2LabCH.tga                     %target_folder%\LabCH2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2labCIE.tga                    %target_folder%\LabCH2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2labHunter.tga                 %target_folder%\LabCH2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2lms.tga                       %target_folder%\LabCH2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2luv.tga                       %target_folder%\LabCH2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2LuvCH.tga                     %target_folder%\LabCH2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2rgb.tga                       %target_folder%\LabCH2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2xyy.tga                       %target_folder%\LabCH2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2xyz.tga                       %target_folder%\LabCH2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2YCgCo.tga                     %target_folder%\LabCH2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2YDbDr.tga                     %target_folder%\LabCH2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2yiq.tga                       %target_folder%\LabCH2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2YPbPr709.tga                  %target_folder%\LabCH2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2yuv601.tga                    %target_folder%\LabCH2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LabCH2yuv709.tga                    %target_folder%\LabCH2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2bgr.tga                      %target_folder%\labCIE2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2cmy.tga                      %target_folder%\labCIE2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2cmyk.tga                     %target_folder%\labCIE2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2hsi.tga                      %target_folder%\labCIE2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2hsl.tga                      %target_folder%\labCIE2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2hsv.tga                      %target_folder%\labCIE2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2hwb.tga                      %target_folder%\labCIE2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2LabCH.tga                    %target_folder%\labCIE2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2labCIE.tga                   %target_folder%\labCIE2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2labHunter.tga                %target_folder%\labCIE2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2lms.tga                      %target_folder%\labCIE2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2luv.tga                      %target_folder%\labCIE2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2LuvCH.tga                    %target_folder%\labCIE2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2rgb.tga                      %target_folder%\labCIE2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2xyy.tga                      %target_folder%\labCIE2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2xyz.tga                      %target_folder%\labCIE2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2YCgCo.tga                    %target_folder%\labCIE2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2YDbDr.tga                    %target_folder%\labCIE2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2yiq.tga                      %target_folder%\labCIE2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2YPbPr709.tga                 %target_folder%\labCIE2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2yuv601.tga                   %target_folder%\labCIE2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labCIE2yuv709.tga                   %target_folder%\labCIE2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2bgr.tga                   %target_folder%\labHunter2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2cmy.tga                   %target_folder%\labHunter2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2cmyk.tga                  %target_folder%\labHunter2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2hsi.tga                   %target_folder%\labHunter2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2hsl.tga                   %target_folder%\labHunter2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2hsv.tga                   %target_folder%\labHunter2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2hwb.tga                   %target_folder%\labHunter2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2LabCH.tga                 %target_folder%\labHunter2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2labCIE.tga                %target_folder%\labHunter2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2labHunter.tga             %target_folder%\labHunter2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2lms.tga                   %target_folder%\labHunter2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2luv.tga                   %target_folder%\labHunter2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2LuvCH.tga                 %target_folder%\labHunter2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2rgb.tga                   %target_folder%\labHunter2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2xyy.tga                   %target_folder%\labHunter2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2xyz.tga                   %target_folder%\labHunter2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2YCgCo.tga                 %target_folder%\labHunter2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2YDbDr.tga                 %target_folder%\labHunter2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2yiq.tga                   %target_folder%\labHunter2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2YPbPr709.tga              %target_folder%\labHunter2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2yuv601.tga                %target_folder%\labHunter2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\labHunter2yuv709.tga                %target_folder%\labHunter2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2bgr.tga                         %target_folder%\lms2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2cmy.tga                         %target_folder%\lms2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2cmyk.tga                        %target_folder%\lms2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2hsi.tga                         %target_folder%\lms2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2hsl.tga                         %target_folder%\lms2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2hsv.tga                         %target_folder%\lms2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2hwb.tga                         %target_folder%\lms2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2LabCH.tga                       %target_folder%\lms2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2labCIE.tga                      %target_folder%\lms2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2labHunter.tga                   %target_folder%\lms2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2lms.tga                         %target_folder%\lms2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2luv.tga                         %target_folder%\lms2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2LuvCH.tga                       %target_folder%\lms2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2rgb.tga                         %target_folder%\lms2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2xyy.tga                         %target_folder%\lms2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2xyz.tga                         %target_folder%\lms2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2YCgCo.tga                       %target_folder%\lms2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2YDbDr.tga                       %target_folder%\lms2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2yiq.tga                         %target_folder%\lms2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2YPbPr709.tga                    %target_folder%\lms2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2yuv601.tga                      %target_folder%\lms2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\lms2yuv709.tga                      %target_folder%\lms2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2bgr.tga                         %target_folder%\luv2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2cmy.tga                         %target_folder%\luv2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2cmyk.tga                        %target_folder%\luv2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2hsi.tga                         %target_folder%\luv2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2hsl.tga                         %target_folder%\luv2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2hsv.tga                         %target_folder%\luv2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2hwb.tga                         %target_folder%\luv2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2LabCH.tga                       %target_folder%\luv2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2labCIE.tga                      %target_folder%\luv2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2labHunter.tga                   %target_folder%\luv2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2lms.tga                         %target_folder%\luv2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2luv.tga                         %target_folder%\luv2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2LuvCH.tga                       %target_folder%\luv2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2rgb.tga                         %target_folder%\luv2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2xyy.tga                         %target_folder%\luv2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2xyz.tga                         %target_folder%\luv2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2YCgCo.tga                       %target_folder%\luv2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2YDbDr.tga                       %target_folder%\luv2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2yiq.tga                         %target_folder%\luv2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2YPbPr709.tga                    %target_folder%\luv2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2yuv601.tga                      %target_folder%\luv2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\luv2yuv709.tga                      %target_folder%\luv2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2bgr.tga                       %target_folder%\LuvCH2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2cmy.tga                       %target_folder%\LuvCH2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2cmyk.tga                      %target_folder%\LuvCH2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2hsi.tga                       %target_folder%\LuvCH2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2hsl.tga                       %target_folder%\LuvCH2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2hsv.tga                       %target_folder%\LuvCH2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2hwb.tga                       %target_folder%\LuvCH2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2LabCH.tga                     %target_folder%\LuvCH2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2labCIE.tga                    %target_folder%\LuvCH2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2labHunter.tga                 %target_folder%\LuvCH2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2lms.tga                       %target_folder%\LuvCH2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2luv.tga                       %target_folder%\LuvCH2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2LuvCH.tga                     %target_folder%\LuvCH2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2rgb.tga                       %target_folder%\LuvCH2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2xyy.tga                       %target_folder%\LuvCH2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2xyz.tga                       %target_folder%\LuvCH2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2YCgCo.tga                     %target_folder%\LuvCH2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2YDbDr.tga                     %target_folder%\LuvCH2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2yiq.tga                       %target_folder%\LuvCH2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2YPbPr709.tga                  %target_folder%\LuvCH2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2yuv601.tga                    %target_folder%\LuvCH2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCH2yuv709.tga                    %target_folder%\LuvCH2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\LuvCHlabHunter.tga                  %target_folder%\LuvCHlabHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2bgr.tga                         %target_folder%\rgb2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2cmy.tga                         %target_folder%\rgb2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2cmyk.tga                        %target_folder%\rgb2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2hsi.tga                         %target_folder%\rgb2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2hsl.tga                         %target_folder%\rgb2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2hsv.tga                         %target_folder%\rgb2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2hwb.tga                         %target_folder%\rgb2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2LabCH.tga                       %target_folder%\rgb2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2labCIE.tga                      %target_folder%\rgb2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2labHunter.tga                   %target_folder%\rgb2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2lms.tga                         %target_folder%\rgb2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2luv.tga                         %target_folder%\rgb2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2LuvCH.tga                       %target_folder%\rgb2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2rgb.tga                         %target_folder%\rgb2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2xyy.tga                         %target_folder%\rgb2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2xyz.tga                         %target_folder%\rgb2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2YCgCo.tga                       %target_folder%\rgb2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2YDbDr.tga                       %target_folder%\rgb2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2yiq.tga                         %target_folder%\rgb2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2YPbPr709.tga                    %target_folder%\rgb2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2yuv601.tga                      %target_folder%\rgb2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\rgb2yuv709.tga                      %target_folder%\rgb2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2bgr.tga                         %target_folder%\xyy2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2cmy.tga                         %target_folder%\xyy2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2cmyk.tga                        %target_folder%\xyy2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2hsi.tga                         %target_folder%\xyy2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2hsl.tga                         %target_folder%\xyy2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2hsv.tga                         %target_folder%\xyy2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2hwb.tga                         %target_folder%\xyy2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2LabCH.tga                       %target_folder%\xyy2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2labCIE.tga                      %target_folder%\xyy2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2labHunter.tga                   %target_folder%\xyy2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2lms.tga                         %target_folder%\xyy2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2luv.tga                         %target_folder%\xyy2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2LuvCH.tga                       %target_folder%\xyy2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2rgb.tga                         %target_folder%\xyy2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2xyy.tga                         %target_folder%\xyy2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2xyz.tga                         %target_folder%\xyy2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2YCgCo.tga                       %target_folder%\xyy2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2YDbDr.tga                       %target_folder%\xyy2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2yiq.tga                         %target_folder%\xyy2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2YPbPr709.tga                    %target_folder%\xyy2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2yuv601.tga                      %target_folder%\xyy2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyy2yuv709.tga                      %target_folder%\xyy2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2bgr.tga                         %target_folder%\xyz2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2cmy.tga                         %target_folder%\xyz2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2cmyk.tga                        %target_folder%\xyz2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2hsi.tga                         %target_folder%\xyz2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2hsl.tga                         %target_folder%\xyz2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2hsv.tga                         %target_folder%\xyz2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2hwb.tga                         %target_folder%\xyz2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2LabCH.tga                       %target_folder%\xyz2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2labCIE.tga                      %target_folder%\xyz2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2labHunter.tga                   %target_folder%\xyz2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2lms.tga                         %target_folder%\xyz2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2luv.tga                         %target_folder%\xyz2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2LuvCH.tga                       %target_folder%\xyz2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2rgb.tga                         %target_folder%\xyz2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2xyy.tga                         %target_folder%\xyz2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2xyz.tga                         %target_folder%\xyz2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2YCgCo.tga                       %target_folder%\xyz2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2YDbDr.tga                       %target_folder%\xyz2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2yiq.tga                         %target_folder%\xyz2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2YPbPr709.tga                    %target_folder%\xyz2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2yuv601.tga                      %target_folder%\xyz2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\xyz2yuv709.tga                      %target_folder%\xyz2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2bgr.tga                       %target_folder%\YCgCo2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2cmy.tga                       %target_folder%\YCgCo2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2cmyk.tga                      %target_folder%\YCgCo2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2hsi.tga                       %target_folder%\YCgCo2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2hsl.tga                       %target_folder%\YCgCo2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2hsv.tga                       %target_folder%\YCgCo2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2hwb.tga                       %target_folder%\YCgCo2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2LabCH.tga                     %target_folder%\YCgCo2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2labCIE.tga                    %target_folder%\YCgCo2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2labHunter.tga                 %target_folder%\YCgCo2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2lms.tga                       %target_folder%\YCgCo2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2luv.tga                       %target_folder%\YCgCo2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2LuvCH.tga                     %target_folder%\YCgCo2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2rgb.tga                       %target_folder%\YCgCo2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2xyy.tga                       %target_folder%\YCgCo2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2xyz.tga                       %target_folder%\YCgCo2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2YCgCo.tga                     %target_folder%\YCgCo2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2YDbDr.tga                     %target_folder%\YCgCo2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2yiq.tga                       %target_folder%\YCgCo2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2YPbPr709.tga                  %target_folder%\YCgCo2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2yuv601.tga                    %target_folder%\YCgCo2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YCgCo2yuv709.tga                    %target_folder%\YCgCo2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2bgr.tga                       %target_folder%\YDbDr2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2cmy.tga                       %target_folder%\YDbDr2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2cmyk.tga                      %target_folder%\YDbDr2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2hsi.tga                       %target_folder%\YDbDr2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2hsl.tga                       %target_folder%\YDbDr2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2hsv.tga                       %target_folder%\YDbDr2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2hwb.tga                       %target_folder%\YDbDr2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2LabCH.tga                     %target_folder%\YDbDr2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2labCIE.tga                    %target_folder%\YDbDr2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2labHunter.tga                 %target_folder%\YDbDr2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2lms.tga                       %target_folder%\YDbDr2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2luv.tga                       %target_folder%\YDbDr2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2LuvCH.tga                     %target_folder%\YDbDr2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2rgb.tga                       %target_folder%\YDbDr2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2xyy.tga                       %target_folder%\YDbDr2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2xyz.tga                       %target_folder%\YDbDr2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2YCgCo.tga                     %target_folder%\YDbDr2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2YDbDr.tga                     %target_folder%\YDbDr2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2yiq.tga                       %target_folder%\YDbDr2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2YPbPr709.tga                  %target_folder%\YDbDr2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2yuv601.tga                    %target_folder%\YDbDr2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YDbDr2yuv709.tga                    %target_folder%\YDbDr2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2bgr.tga                         %target_folder%\yiq2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2cmy.tga                         %target_folder%\yiq2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2cmyk.tga                        %target_folder%\yiq2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2hsi.tga                         %target_folder%\yiq2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2hsl.tga                         %target_folder%\yiq2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2hsv.tga                         %target_folder%\yiq2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2hwb.tga                         %target_folder%\yiq2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2LabCH.tga                       %target_folder%\yiq2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2labCIE.tga                      %target_folder%\yiq2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2labHunter.tga                   %target_folder%\yiq2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2lms.tga                         %target_folder%\yiq2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2luv.tga                         %target_folder%\yiq2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2LuvCH.tga                       %target_folder%\yiq2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2rgb.tga                         %target_folder%\yiq2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2xyy.tga                         %target_folder%\yiq2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2xyz.tga                         %target_folder%\yiq2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2YCgCo.tga                       %target_folder%\yiq2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2YDbDr.tga                       %target_folder%\yiq2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2yiq.tga                         %target_folder%\yiq2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2YPbPr709.tga                    %target_folder%\yiq2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2yuv601.tga                      %target_folder%\yiq2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yiq2yuv709.tga                      %target_folder%\yiq2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2bgr.tga                   %target_folder%\YPbPr709_2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2cmy.tga                   %target_folder%\YPbPr709_2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2cmyk.tga                  %target_folder%\YPbPr709_2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2hsi.tga                   %target_folder%\YPbPr709_2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2hsl.tga                   %target_folder%\YPbPr709_2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2hsv.tga                   %target_folder%\YPbPr709_2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2hwb.tga                   %target_folder%\YPbPr709_2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2LabCH.tga                 %target_folder%\YPbPr709_2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2labCIE.tga                %target_folder%\YPbPr709_2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2labHunter.tga             %target_folder%\YPbPr709_2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2lms.tga                   %target_folder%\YPbPr709_2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2luv.tga                   %target_folder%\YPbPr709_2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2LuvCH.tga                 %target_folder%\YPbPr709_2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2rgb.tga                   %target_folder%\YPbPr709_2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2xyy.tga                   %target_folder%\YPbPr709_2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2xyz.tga                   %target_folder%\YPbPr709_2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2YCgCo.tga                 %target_folder%\YPbPr709_2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2YDbDr.tga                 %target_folder%\YPbPr709_2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2yiq.tga                   %target_folder%\YPbPr709_2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2YPbPr709.tga              %target_folder%\YPbPr709_2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2yuv601.tga                %target_folder%\YPbPr709_2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\YPbPr709_2yuv709.tga                %target_folder%\YPbPr709_2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2bgr.tga                     %target_folder%\yuv601_2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2cmy.tga                     %target_folder%\yuv601_2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2cmyk.tga                    %target_folder%\yuv601_2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2hsi.tga                     %target_folder%\yuv601_2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2hsl.tga                     %target_folder%\yuv601_2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2hsv.tga                     %target_folder%\yuv601_2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2hwb.tga                     %target_folder%\yuv601_2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2LabCH.tga                   %target_folder%\yuv601_2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2labCIE.tga                  %target_folder%\yuv601_2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2labHunter.tga               %target_folder%\yuv601_2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2lms.tga                     %target_folder%\yuv601_2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2luv.tga                     %target_folder%\yuv601_2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2LuvCH.tga                   %target_folder%\yuv601_2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2rgb.tga                     %target_folder%\yuv601_2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2xyy.tga                     %target_folder%\yuv601_2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2xyz.tga                     %target_folder%\yuv601_2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2YCgCo.tga                   %target_folder%\yuv601_2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2YDbDr.tga                   %target_folder%\yuv601_2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2yiq.tga                     %target_folder%\yuv601_2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2YPbPr709.tga                %target_folder%\yuv601_2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2yuv601.tga                  %target_folder%\yuv601_2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv601_2yuv709.tga                  %target_folder%\yuv601_2yuv709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2bgr.tga                     %target_folder%\yuv709_2bgr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2cmy.tga                     %target_folder%\yuv709_2cmy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2cmyk.tga                    %target_folder%\yuv709_2cmyk.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2hsi.tga                     %target_folder%\yuv709_2hsi.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2hsl.tga                     %target_folder%\yuv709_2hsl.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2hsv.tga                     %target_folder%\yuv709_2hsv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2hwb.tga                     %target_folder%\yuv709_2hwb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2LabCH.tga                   %target_folder%\yuv709_2LabCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2labCIE.tga                  %target_folder%\yuv709_2labCIE.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2labHunter.tga               %target_folder%\yuv709_2labHunter.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2lms.tga                     %target_folder%\yuv709_2lms.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2luv.tga                     %target_folder%\yuv709_2luv.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2LuvCH.tga                   %target_folder%\yuv709_2LuvCH.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2rgb.tga                     %target_folder%\yuv709_2rgb.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2xyy.tga                     %target_folder%\yuv709_2xyy.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2xyz.tga                     %target_folder%\yuv709_2xyz.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2YCgCo.tga                   %target_folder%\yuv709_2YCgCo.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2YDbDr.tga                   %target_folder%\yuv709_2YDbDr.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2yiq.tga                     %target_folder%\yuv709_2yiq.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2YPbPr709.tga                %target_folder%\yuv709_2YPbPr709.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2yuv601.tga                  %target_folder%\yuv709_2yuv601.tga
%program_TC%  %left_folder%\bgr_double_2bgr.tga  %right_folder%\yuv709_2yuv709.tga                  %target_folder%\yuv709_2yuv709.tga


pause