#!/bin/bash

pwd

./YDbDr2cmy.exe
./YDbDr2cmyk.exe
./YDbDr2gray.exe
./YDbDr2hsi.exe
./YDbDr2hsl.exe
./YDbDr2hsv.exe
./YDbDr2hwb.exe
./YDbDr2lab.exe
./YDbDr2LabCH.exe
./YDbDr2lms.exe
./YDbDr2lms_BFD.exe
./YDbDr2lms_K65.exe
./YDbDr2lms_KE.exe
./YDbDr2lms_MCAT02.exe
./YDbDr2luv.exe
./YDbDr2LuvCH.exe
./YDbDr2rgb.exe
./YDbDr2xyy.exe
./YDbDr2xyz.exe
./YDbDr2YCgCo.exe
./YDbDr2YDbDr.exe
./YDbDr2yiq.exe
./YDbDr2YPbPr.exe
./YDbDr2YPbPr2020.exe
./YDbDr2YPbPr601.exe
./YDbDr2YPbPr709.exe
./YDbDr2yuv.exe
./YDbDr2yuv601.exe
./YDbDr2yuv709.exe