#!/bin/bash

pwd

./gray2cmy.exe
./gray2cmyk.exe
./gray2gray.exe
./gray2hsi.exe
./gray2hsl.exe
./gray2hsv.exe
./gray2hwb.exe
./gray2lab.exe
./gray2LabCH.exe
./gray2lms.exe
./gray2lms_BFD.exe
./gray2lms_K65.exe
./gray2lms_KE.exe
./gray2lms_MCAT02.exe
./gray2luv.exe
./gray2LuvCH.exe
./gray2rgb.exe
./gray2xyy.exe
./gray2xyz.exe
./gray2YCgCo.exe
./gray2YDbDr.exe
./gray2yiq.exe
./gray2YPbPr.exe
./gray2YPbPr2020.exe
./gray2YPbPr601.exe
./gray2YPbPr709.exe
./gray2yuv.exe
./gray2yuv601.exe
./gray2yuv709.exe