#include "./double.hpp"
#include "./float.hpp"
#include "./ldouble.hpp"
#include "./uint16.hpp"
#include "./uint32.hpp"
#include "./uint64.hpp"
#include "./uint8.hpp"
#include "./scramble3.hpp"
#include "./scramble4.hpp"

#include "./split332.hpp"
#include "./split422.hpp"
#include "./split556.hpp"
#include "./split565.hpp"
#include "./split655.hpp"
#include "./splitAAA2.hpp"
