#include "./cmy.hpp"
#include "./cmyk.hpp"
#include "./gray.hpp"
#include "./hsl.hpp"
#include "./hsv.hpp"
#include "./rgb.hpp"
#include "./xyz.hpp"
#include "./yiq.hpp"
#include "./yuv.hpp"

#include "./YCbCr.hpp"
#include "./YCgCo.hpp"
#include "./YDbDr.hpp"
#include "./YPbPr.hpp"