cd out

tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmy2cmy.tga                check\cmy2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmy2cmyk.tga               check\cmy2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmy2hsi.tga                check\cmy2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmy2hsl.tga                check\cmy2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmy2hsv.tga                check\cmy2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmy2rgb.tga                check\cmy2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmy2xyz.tga                check\cmy2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmy2YCgCo.tga              check\cmy2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmy2YDbDr.tga              check\cmy2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmy2yiq.tga                check\cmy2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmy2YPbPr709.tga           check\cmy2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmy2yuv709.tga             check\cmy2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmyk2cmy.tga               check\cmyk2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmyk2cmyk.tga              check\cmyk2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmyk2hsi.tga               check\cmyk2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmyk2hsl.tga               check\cmyk2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmyk2hsv.tga               check\cmyk2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmyk2rgb.tga               check\cmyk2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmyk2xyz.tga               check\cmyk2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmyk2YCgCo.tga             check\cmyk2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmyk2YDbDr.tga             check\cmyk2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmyk2yiq.tga               check\cmyk2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmyk2YPbPr709.tga          check\cmyk2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\cmyk2yuv709.tga            check\cmyk2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsi2cmy.tga                check\hsi2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsi2cmyk.tga               check\hsi2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsi2hsi.tga                check\hsi2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsi2hsl.tga                check\hsi2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsi2hsv.tga                check\hsi2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsi2rgb.tga                check\hsi2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsi2xyz.tga                check\hsi2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsi2YCgCo.tga              check\hsi2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsi2YDbDr.tga              check\hsi2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsi2yiq.tga                check\hsi2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsi2YPbPr709.tga           check\hsi2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsi2yuv709.tga             check\hsi2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsl2cmy.tga                check\hsl2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsl2cmyk.tga               check\hsl2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsl2hsi.tga                check\hsl2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsl2hsl.tga                check\hsl2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsl2hsv.tga                check\hsl2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsl2rgb.tga                check\hsl2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsl2xyz.tga                check\hsl2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsl2YCgCo.tga              check\hsl2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsl2YDbDr.tga              check\hsl2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsl2yiq.tga                check\hsl2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsl2YPbPr709.tga           check\hsl2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsl2yuv709.tga             check\hsl2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsv2cmy.tga                check\hsv2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsv2cmyk.tga               check\hsv2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsv2hsi.tga                check\hsv2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsv2hsl.tga                check\hsv2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsv2hsv.tga                check\hsv2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsv2rgb.tga                check\hsv2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsv2xyz.tga                check\hsv2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsv2YCgCo.tga              check\hsv2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsv2YDbDr.tga              check\hsv2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsv2yiq.tga                check\hsv2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsv2YPbPr709.tga           check\hsv2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\hsv2yuv709.tga             check\hsv2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\rgb2cmy.tga                check\rgb2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\rgb2cmyk.tga               check\rgb2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\rgb2hsi.tga                check\rgb2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\rgb2hsl.tga                check\rgb2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\rgb2hsv.tga                check\rgb2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\rgb2rgb.tga                check\rgb2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\rgb2xyz.tga                check\rgb2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\rgb2YCgCo.tga              check\rgb2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\rgb2YDbDr.tga              check\rgb2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\rgb2yiq.tga                check\rgb2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\rgb2YPbPr709.tga           check\rgb2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\rgb2yuv709.tga             check\rgb2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\xyz2cmy.tga                check\xyz2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\xyz2cmyk.tga               check\xyz2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\xyz2hsi.tga                check\xyz2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\xyz2hsl.tga                check\xyz2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\xyz2hsv.tga                check\xyz2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\xyz2rgb.tga                check\xyz2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\xyz2xyz.tga                check\xyz2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\xyz2YCgCo.tga              check\xyz2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\xyz2YDbDr.tga              check\xyz2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\xyz2yiq.tga                check\xyz2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\xyz2YPbPr709.tga           check\xyz2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\xyz2yuv709.tga             check\xyz2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YCgCo2cmy.tga              check\YCgCo2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YCgCo2cmyk.tga             check\YCgCo2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YCgCo2hsi.tga              check\YCgCo2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YCgCo2hsl.tga              check\YCgCo2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YCgCo2hsv.tga              check\YCgCo2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YCgCo2rgb.tga              check\YCgCo2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YCgCo2xyz.tga              check\YCgCo2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YCgCo2YCgCo.tga            check\YCgCo2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YCgCo2YDbDr.tga            check\YCgCo2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YCgCo2yiq.tga              check\YCgCo2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YCgCo2YPbPr709.tga         check\YCgCo2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YCgCo2yuv709.tga           check\YCgCo2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YDbDr2cmy.tga              check\YDbDr2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YDbDr2cmyk.tga             check\YDbDr2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YDbDr2hsi.tga              check\YDbDr2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YDbDr2hsl.tga              check\YDbDr2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YDbDr2hsv.tga              check\YDbDr2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YDbDr2rgb.tga              check\YDbDr2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YDbDr2xyz.tga              check\YDbDr2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YDbDr2YCgCo.tga            check\YDbDr2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YDbDr2YDbDr.tga            check\YDbDr2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YDbDr2yiq.tga              check\YDbDr2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YDbDr2YPbPr709.tga         check\YDbDr2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YDbDr2yuv709.tga           check\YDbDr2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yiq2cmy.tga                check\yiq2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yiq2cmyk.tga               check\yiq2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yiq2hsi.tga                check\yiq2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yiq2hsl.tga                check\yiq2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yiq2hsv.tga                check\yiq2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yiq2rgb.tga                check\yiq2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yiq2xyz.tga                check\yiq2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yiq2YCgCo.tga              check\yiq2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yiq2YDbDr.tga              check\yiq2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yiq2yiq.tga                check\yiq2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yiq2YPbPr709.tga           check\yiq2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yiq2yuv709.tga             check\yiq2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YPbPr709_2cmy.tga          check\YPbPr709_2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YPbPr709_2cmyk.tga         check\YPbPr709_2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YPbPr709_2hsi.tga          check\YPbPr709_2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YPbPr709_2hsl.tga          check\YPbPr709_2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YPbPr709_2hsv.tga          check\YPbPr709_2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YPbPr709_2rgb.tga          check\YPbPr709_2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YPbPr709_2xyz.tga          check\YPbPr709_2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YPbPr709_2YCgCo.tga        check\YPbPr709_2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YPbPr709_2YDbDr.tga        check\YPbPr709_2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YPbPr709_2yiq.tga          check\YPbPr709_2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YPbPr709_2YPbPr709.tga     check\YPbPr709_2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\YPbPr709_2yuv709.tga       check\YPbPr709_2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yuv709_2cmy.tga            check\yuv709_2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yuv709_2cmyk.tga           check\yuv709_2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yuv709_2hsi.tga            check\yuv709_2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yuv709_2hsl.tga            check\yuv709_2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yuv709_2hsv.tga            check\yuv709_2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yuv709_2rgb.tga            check\yuv709_2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yuv709_2xyz.tga            check\yuv709_2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yuv709_2YCgCo.tga          check\yuv709_2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yuv709_2YDbDr.tga          check\yuv709_2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yuv709_2yiq.tga            check\yuv709_2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yuv709_2YPbPr709.tga       check\yuv709_2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga   conv\yuv709_2yuv709.tga         check\yuv709_2yuv709.tga

cd ..