cd out

tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2bgr.tga                  check\bgr2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2cmy.tga                  check\bgr2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2cmyk.tga                 check\bgr2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2gray.tga                 check\bgr2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2hsi.tga                  check\bgr2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2hsl.tga                  check\bgr2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2hsv.tga                  check\bgr2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2lab.tga                  check\bgr2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2lms.tga                  check\bgr2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2luv.tga                  check\bgr2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2rgb.tga                  check\bgr2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2xyy.tga                  check\bgr2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2xyz.tga                  check\bgr2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2YCgCo.tga                check\bgr2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2YDbDr.tga                check\bgr2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2yiq.tga                  check\bgr2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2YPbPr709.tga             check\bgr2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2yuv601.tga               check\bgr2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\bgr2yuv709.tga               check\bgr2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2bgr.tga                  check\cmy2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2cmy.tga                  check\cmy2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2cmyk.tga                 check\cmy2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2gray.tga                 check\cmy2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2hsi.tga                  check\cmy2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2hsl.tga                  check\cmy2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2hsv.tga                  check\cmy2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2lab.tga                  check\cmy2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2lms.tga                  check\cmy2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2luv.tga                  check\cmy2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2rgb.tga                  check\cmy2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2xyy.tga                  check\cmy2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2xyz.tga                  check\cmy2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2YCgCo.tga                check\cmy2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2YDbDr.tga                check\cmy2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2yiq.tga                  check\cmy2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2YPbPr709.tga             check\cmy2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2yuv601.tga               check\cmy2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmy2yuv709.tga               check\cmy2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2bgr.tga                 check\cmyk2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2cmy.tga                 check\cmyk2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2cmyk.tga                check\cmyk2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2gray.tga                check\cmyk2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2hsi.tga                 check\cmyk2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2hsl.tga                 check\cmyk2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2hsv.tga                 check\cmyk2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2lab.tga                 check\cmyk2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2lms.tga                 check\cmyk2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2luv.tga                 check\cmyk2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2rgb.tga                 check\cmyk2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2xyy.tga                 check\cmyk2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2xyz.tga                 check\cmyk2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2YCgCo.tga               check\cmyk2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2YDbDr.tga               check\cmyk2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2yiq.tga                 check\cmyk2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2YPbPr709.tga            check\cmyk2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2yuv601.tga              check\cmyk2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\cmyk2yuv709.tga              check\cmyk2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2bgr.tga                 check\gray2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2cmy.tga                 check\gray2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2cmyk.tga                check\gray2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2gray.tga                check\gray2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2hsi.tga                 check\gray2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2hsl.tga                 check\gray2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2hsv.tga                 check\gray2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2lab.tga                 check\gray2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2lms.tga                 check\gray2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2luv.tga                 check\gray2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2rgb.tga                 check\gray2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2xyy.tga                 check\gray2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2xyz.tga                 check\gray2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2YCgCo.tga               check\gray2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2YDbDr.tga               check\gray2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2yiq.tga                 check\gray2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2YPbPr709.tga            check\gray2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2yuv601.tga              check\gray2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\gray2yuv709.tga              check\gray2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2bgr.tga                  check\hsi2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2cmy.tga                  check\hsi2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2cmyk.tga                 check\hsi2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2gray.tga                 check\hsi2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2hsi.tga                  check\hsi2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2hsl.tga                  check\hsi2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2hsv.tga                  check\hsi2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2lab.tga                  check\hsi2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2lms.tga                  check\hsi2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2luv.tga                  check\hsi2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2rgb.tga                  check\hsi2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2xyy.tga                  check\hsi2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2xyz.tga                  check\hsi2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2YCgCo.tga                check\hsi2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2YDbDr.tga                check\hsi2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2yiq.tga                  check\hsi2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2YPbPr709.tga             check\hsi2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2yuv601.tga               check\hsi2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsi2yuv709.tga               check\hsi2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2bgr.tga                  check\hsl2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2cmy.tga                  check\hsl2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2cmyk.tga                 check\hsl2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2gray.tga                 check\hsl2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2hsi.tga                  check\hsl2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2hsl.tga                  check\hsl2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2hsv.tga                  check\hsl2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2lab.tga                  check\hsl2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2lms.tga                  check\hsl2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2luv.tga                  check\hsl2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2rgb.tga                  check\hsl2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2xyy.tga                  check\hsl2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2xyz.tga                  check\hsl2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2YCgCo.tga                check\hsl2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2YDbDr.tga                check\hsl2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2yiq.tga                  check\hsl2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2YPbPr709.tga             check\hsl2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2yuv601.tga               check\hsl2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsl2yuv709.tga               check\hsl2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2bgr.tga                  check\hsv2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2cmy.tga                  check\hsv2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2cmyk.tga                 check\hsv2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2gray.tga                 check\hsv2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2hsi.tga                  check\hsv2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2hsl.tga                  check\hsv2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2hsv.tga                  check\hsv2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2lab.tga                  check\hsv2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2lms.tga                  check\hsv2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2luv.tga                  check\hsv2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2rgb.tga                  check\hsv2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2xyy.tga                  check\hsv2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2xyz.tga                  check\hsv2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2YCgCo.tga                check\hsv2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2YDbDr.tga                check\hsv2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2yiq.tga                  check\hsv2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2YPbPr709.tga             check\hsv2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2yuv601.tga               check\hsv2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\hsv2yuv709.tga               check\hsv2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2bgr.tga                  check\lab2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2cmy.tga                  check\lab2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2cmyk.tga                 check\lab2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2gray.tga                 check\lab2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2hsi.tga                  check\lab2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2hsl.tga                  check\lab2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2hsv.tga                  check\lab2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2lab.tga                  check\lab2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2lms.tga                  check\lab2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2luv.tga                  check\lab2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2rgb.tga                  check\lab2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2xyy.tga                  check\lab2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2xyz.tga                  check\lab2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2YCgCo.tga                check\lab2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2YDbDr.tga                check\lab2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2yiq.tga                  check\lab2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2YPbPr709.tga             check\lab2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2yuv601.tga               check\lab2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lab2yuv709.tga               check\lab2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2bgr.tga                  check\lms2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2cmy.tga                  check\lms2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2cmyk.tga                 check\lms2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2gray.tga                 check\lms2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2hsi.tga                  check\lms2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2hsl.tga                  check\lms2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2hsv.tga                  check\lms2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2lab.tga                  check\lms2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2lms.tga                  check\lms2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2luv.tga                  check\lms2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2rgb.tga                  check\lms2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2xyy.tga                  check\lms2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2xyz.tga                  check\lms2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2YCgCo.tga                check\lms2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2YDbDr.tga                check\lms2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2yiq.tga                  check\lms2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2YPbPr709.tga             check\lms2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2yuv601.tga               check\lms2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\lms2yuv709.tga               check\lms2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2bgr.tga                  check\luv2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2cmy.tga                  check\luv2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2cmyk.tga                 check\luv2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2gray.tga                 check\luv2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2hsi.tga                  check\luv2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2hsl.tga                  check\luv2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2hsv.tga                  check\luv2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2lab.tga                  check\luv2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2lms.tga                  check\luv2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2luv.tga                  check\luv2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2rgb.tga                  check\luv2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2xyy.tga                  check\luv2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2xyz.tga                  check\luv2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2YCgCo.tga                check\luv2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2YDbDr.tga                check\luv2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2yiq.tga                  check\luv2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2YPbPr709.tga             check\luv2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2yuv601.tga               check\luv2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\luv2yuv709.tga               check\luv2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2bgr.tga                  check\rgb2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2cmy.tga                  check\rgb2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2cmyk.tga                 check\rgb2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2gray.tga                 check\rgb2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2hsi.tga                  check\rgb2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2hsl.tga                  check\rgb2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2hsv.tga                  check\rgb2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2lab.tga                  check\rgb2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2lms.tga                  check\rgb2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2luv.tga                  check\rgb2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2rgb.tga                  check\rgb2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2xyy.tga                  check\rgb2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2xyz.tga                  check\rgb2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2YCgCo.tga                check\rgb2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2YDbDr.tga                check\rgb2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2yiq.tga                  check\rgb2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2YPbPr709.tga             check\rgb2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2yuv601.tga               check\rgb2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\rgb2yuv709.tga               check\rgb2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2bgr.tga                  check\xyy2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2cmy.tga                  check\xyy2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2cmyk.tga                 check\xyy2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2gray.tga                 check\xyy2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2hsi.tga                  check\xyy2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2hsl.tga                  check\xyy2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2hsv.tga                  check\xyy2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2lab.tga                  check\xyy2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2lms.tga                  check\xyy2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2luv.tga                  check\xyy2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2rgb.tga                  check\xyy2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2xyy.tga                  check\xyy2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2xyz.tga                  check\xyy2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2YCgCo.tga                check\xyy2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2YDbDr.tga                check\xyy2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2yiq.tga                  check\xyy2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2YPbPr709.tga             check\xyy2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2yuv601.tga               check\xyy2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyy2yuv709.tga               check\xyy2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2bgr.tga                  check\xyz2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2cmy.tga                  check\xyz2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2cmyk.tga                 check\xyz2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2gray.tga                 check\xyz2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2hsi.tga                  check\xyz2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2hsl.tga                  check\xyz2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2hsv.tga                  check\xyz2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2lab.tga                  check\xyz2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2lms.tga                  check\xyz2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2luv.tga                  check\xyz2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2rgb.tga                  check\xyz2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2xyy.tga                  check\xyz2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2xyz.tga                  check\xyz2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2YCgCo.tga                check\xyz2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2YDbDr.tga                check\xyz2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2yiq.tga                  check\xyz2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2YPbPr709.tga             check\xyz2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2yuv601.tga               check\xyz2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\xyz2yuv709.tga               check\xyz2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2bgr.tga                check\YCgCo2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2cmy.tga                check\YCgCo2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2cmyk.tga               check\YCgCo2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2gray.tga               check\YCgCo2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2hsi.tga                check\YCgCo2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2hsl.tga                check\YCgCo2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2hsv.tga                check\YCgCo2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2lab.tga                check\YCgCo2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2lms.tga                check\YCgCo2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2luv.tga                check\YCgCo2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2rgb.tga                check\YCgCo2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2xyy.tga                check\YCgCo2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2xyz.tga                check\YCgCo2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2YCgCo.tga              check\YCgCo2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2YDbDr.tga              check\YCgCo2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2yiq.tga                check\YCgCo2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2YPbPr709.tga           check\YCgCo2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2yuv601.tga             check\YCgCo2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YCgCo2yuv709.tga             check\YCgCo2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2bgr.tga                check\YDbDr2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2cmy.tga                check\YDbDr2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2cmyk.tga               check\YDbDr2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2gray.tga               check\YDbDr2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2hsi.tga                check\YDbDr2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2hsl.tga                check\YDbDr2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2hsv.tga                check\YDbDr2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2lab.tga                check\YDbDr2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2lms.tga                check\YDbDr2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2luv.tga                check\YDbDr2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2rgb.tga                check\YDbDr2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2xyy.tga                check\YDbDr2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2xyz.tga                check\YDbDr2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2YCgCo.tga              check\YDbDr2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2YDbDr.tga              check\YDbDr2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2yiq.tga                check\YDbDr2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2YPbPr709.tga           check\YDbDr2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2yuv601.tga             check\YDbDr2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YDbDr2yuv709.tga             check\YDbDr2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2bgr.tga                  check\yiq2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2cmy.tga                  check\yiq2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2cmyk.tga                 check\yiq2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2gray.tga                 check\yiq2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2hsi.tga                  check\yiq2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2hsl.tga                  check\yiq2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2hsv.tga                  check\yiq2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2lab.tga                  check\yiq2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2lms.tga                  check\yiq2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2luv.tga                  check\yiq2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2rgb.tga                  check\yiq2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2xyy.tga                  check\yiq2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2xyz.tga                  check\yiq2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2YCgCo.tga                check\yiq2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2YDbDr.tga                check\yiq2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2yiq.tga                  check\yiq2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2YPbPr709.tga             check\yiq2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2yuv601.tga               check\yiq2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yiq2yuv709.tga               check\yiq2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2bgr.tga            check\YPbPr709_2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2cmy.tga            check\YPbPr709_2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2cmyk.tga           check\YPbPr709_2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2gray.tga           check\YPbPr709_2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2hsi.tga            check\YPbPr709_2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2hsl.tga            check\YPbPr709_2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2hsv.tga            check\YPbPr709_2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2lab.tga            check\YPbPr709_2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2lms.tga            check\YPbPr709_2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2luv.tga            check\YPbPr709_2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2rgb.tga            check\YPbPr709_2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2xyy.tga            check\YPbPr709_2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2xyz.tga            check\YPbPr709_2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2YCgCo.tga          check\YPbPr709_2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2YDbDr.tga          check\YPbPr709_2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2yiq.tga            check\YPbPr709_2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2YPbPr709.tga       check\YPbPr709_2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2yuv601.tga         check\YPbPr709_2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\YPbPr709_2yuv709.tga         check\YPbPr709_2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2bgr.tga              check\yuv601_2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2cmy.tga              check\yuv601_2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2cmyk.tga             check\yuv601_2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2gray.tga             check\yuv601_2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2hsi.tga              check\yuv601_2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2hsl.tga              check\yuv601_2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2hsv.tga              check\yuv601_2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2lab.tga              check\yuv601_2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2lms.tga              check\yuv601_2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2luv.tga              check\yuv601_2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2rgb.tga              check\yuv601_2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2xyy.tga              check\yuv601_2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2xyz.tga              check\yuv601_2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2YCgCo.tga            check\yuv601_2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2YDbDr.tga            check\yuv601_2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2yiq.tga              check\yuv601_2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2YPbPr709.tga         check\yuv601_2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2yuv601.tga           check\yuv601_2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv601_2yuv709.tga           check\yuv601_2yuv709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2bgr.tga              check\yuv709_2bgr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2cmy.tga              check\yuv709_2cmy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2cmyk.tga             check\yuv709_2cmyk.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2gray.tga             check\yuv709_2gray.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2hsi.tga              check\yuv709_2hsi.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2hsl.tga              check\yuv709_2hsl.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2hsv.tga              check\yuv709_2hsv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2lab.tga              check\yuv709_2lab.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2lms.tga              check\yuv709_2lms.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2luv.tga              check\yuv709_2luv.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2rgb.tga              check\yuv709_2rgb.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2xyy.tga              check\yuv709_2xyy.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2xyz.tga              check\yuv709_2xyz.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2YCgCo.tga            check\yuv709_2YCgCo.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2YDbDr.tga            check\yuv709_2YDbDr.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2yiq.tga              check\yuv709_2yiq.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2YPbPr709.tga         check\yuv709_2YPbPr709.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2yuv601.tga           check\yuv709_2yuv601.tga
tc.exe  conv-rgb\bgr_double_2bgr.tga  conv\yuv709_2yuv709.tga           check\yuv709_2yuv709.tga