
import nucleotide

#make setting
settings = nucleotide.Settings( )

settings.set_custom( 'RTL', 'dynamic' )
settings.set_custom( 'architecture', 'i386' )
settings.set_custom( 'configuration', 'release' )
settings.set_custom( 'compiler_version_msvc', '14.0' ) #11, 12, 14
settings.set_custom( 'pp2f', 'false' )

settings.set_custom( 'configuration',   ARGUMENTS.get( 'configuration', settings.get_custom( 'configuration' ) ) ) 
settings.set_custom( 'pp2f',            ARGUMENTS.get( 'pp2f', settings.get_custom( 'pp2f' ) ) ) 

#Accumulate 
# Nothing to accumulate. This is minimal

# Call
product = SConscript('./SConscript', exports=[ 'settings' ] )

#Make it default
Default( product )

