
import nucleotide

#make setting
settings = nucleotide.Settings( )
settings.set_custom( 'configuration', 'release' )
settings.set_custom( 'compiler_version_msvc', '14.0' )

settings.set_custom( 'configuration',   ARGUMENTS.get( 'configuration', settings.get_custom( 'configuration' ) ) ) 

#Accumulate 
# Nothing to accumulate. This is minimal

# Call
product = SConscript('./SConscript', exports=[ 'settings' ] )

#Make it defualt
Default( product )


