import os
import nucleotide


Import('settings')

name_full = 'test'

settings.set_custom( 'RTL', 'dynamic' )
settings.set_custom( 'architecture', 'i386' )

configuration = settings.get_custom( 'configuration' )

directory_pdb = './out/bin-' + configuration + '/'
directory_obj = './out/bin-' + configuration + '/'
directory_exe = './out/'

# Accumulate Atoms
settings.accumulate( 'include', { '0' : '../../src' } )
settings.accumulate( 'architecture', { 'name' : settings.get_custom( 'architecture' ) } )
settings.accumulate( 'exception' )
settings.accumulate( 'source:c++', { 'dialect' : 'c++11' } )
settings.accumulate( 'RTTI', { 'enable': 'false' } )
settings.accumulate( 'compiler:configuration', { 'name'          : configuration  } )
settings.accumulate( 'compiler:optimisation',  { 'configuration' : configuration  } )
settings.accumulate( 'compiler:version',  { 'msvc' : [ settings.get_custom( 'compiler_version_msvc' ) ] } )

settings.accumulate( 'PDB', { 'configuration': configuration , 'synchronous' : 'false', 'file-name': os.path.join( directory_pdb, name_full + '.pdb' ) } )
settings.accumulate( 'RTL', { 'configuration' : configuration, 'type': settings.get_custom( 'RTL' ) } )

#settings.accumulate( 'macro',  { 'name' : 'COLOR_USE_PP2FILE'  } )

# Accumulate source
envObject = nucleotide.Environment( settings ).native()

source = []
source +=   [
     envObject.StaticObject( target =  os.path.join( directory_obj, 'main'             ) + envObject[ 'OBJSUFFIX' ],  source = './main.cpp'       )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'conversion'       ) + envObject[ 'OBJSUFFIX' ],  source = './conversion.cpp' )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'targa'            ) + envObject[ 'OBJSUFFIX' ],  source = './targa.cpp'      )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'make'             ) + envObject[ 'OBJSUFFIX' ],  source = './make.cpp'       )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'bound'            ) + envObject[ 'OBJSUFFIX' ],  source = './bound.cpp'      )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'sizeof'           ) + envObject[ 'OBJSUFFIX' ],  source = './sizeof.cpp'     )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'selfie'           ) + envObject[ 'OBJSUFFIX' ],  source = './selfie.cpp'     )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'set_invoke'       ) + envObject[ 'OBJSUFFIX' ],  source = './set_invoke.cpp' )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'get_invoke'       ) + envObject[ 'OBJSUFFIX' ],  source = './get_invoke.cpp' )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'get_test'         ) + envObject[ 'OBJSUFFIX' ],  source = './get_test.cpp'   )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'gray_test'        ) + envObject[ 'OBJSUFFIX' ],  source = './gray_test.cpp'  )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'decompose'        ) + envObject[ 'OBJSUFFIX' ],  source = './decompose.cpp'  )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'place'            ) + envObject[ 'OBJSUFFIX' ],  source = './place.cpp'      )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'convsemi'         ) + envObject[ 'OBJSUFFIX' ],  source = './convsemi.cpp'   )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'image'            ) + envObject[ 'OBJSUFFIX' ],  source = './image.cpp'      )

   , envObject.StaticObject( target =  os.path.join( directory_obj, 'operation/gamma'      ) + envObject[ 'OBJSUFFIX' ],  source = './operation/gamma.cpp'      )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'operation/bias'       ) + envObject[ 'OBJSUFFIX' ],  source = './operation/bias.cpp'       )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'operation/gain'       ) + envObject[ 'OBJSUFFIX' ],  source = './operation/gain.cpp'       )
   , envObject.StaticObject( target =  os.path.join( directory_obj, 'operation/operation'  ) + envObject[ 'OBJSUFFIX' ],  source = './operation/operation.cpp'  )

   ]

# Make native environment
envProgram = nucleotide.Environment( settings ).native()

# Create program
program = envProgram.Program( target =  directory_exe+ 'test' + envProgram['PROGSUFFIX'], source = source )

# ... and return!
Return( 'program' )
