#include "./black.hpp"
#include "./gray.hpp"
#include "./white.hpp"

#include "./red.hpp"
#include "./green.hpp"
#include "./blue.hpp"

#include "./cyan.hpp"
#include "./magenta.hpp"
#include "./yellow.hpp"


#include "./aqua.hpp"
#include "./fuchsia.hpp"
#include "./lime.hpp"

#include "./maroon.hpp"
#include "./navy.hpp"
#include "./olive.hpp"
#include "./orange.hpp"
#include "./purple.hpp"

#include "./silver.hpp"
#include "./teal.hpp"
#include "./violet.hpp"



#include "./aquamarine.hpp"
#include "./azure.hpp"
#include "./beige.hpp"
#include "./bisque.hpp"
#include "./brown.hpp"
#include "./chocolate.hpp"
#include "./coral.hpp"
#include "./crimson.hpp"
#include "./gainsboro.hpp"
#include "./gold.hpp"
#include "./indigo.hpp"
#include "./ivory.hpp"
#include "./khaki.hpp"
#include "./lavender.hpp"
#include "./linen.hpp"
#include "./moccasin.hpp"
#include "./orchid.hpp"
#include "./peru.hpp"
#include "./pink.hpp"
#include "./plum.hpp"
#include "./salmon.hpp"
#include "./sienna.hpp"
#include "./snow.hpp"
#include "./tan.hpp"
#include "./thistle.hpp"
#include "./tomato.hpp"
#include "./turquoise.hpp"
#include "./wheat.hpp"
