#!/bin/bash

pwd

./LuvCH2cmy.exe
./LuvCH2cmyk.exe
./LuvCH2gray.exe
./LuvCH2hsi.exe
./LuvCH2hsl.exe
./LuvCH2hsv.exe
./LuvCH2hwb.exe
./LuvCH2lab.exe
./LuvCH2LabCH.exe
./LuvCH2lms.exe
./LuvCH2lms_BFD.exe
./LuvCH2lms_K65.exe
./LuvCH2lms_KE.exe
./LuvCH2lms_MCAT02.exe
./LuvCH2luv.exe
./LuvCH2LuvCH.exe
./LuvCH2rgb.exe
./LuvCH2xyy.exe
./LuvCH2xyz.exe
./LuvCH2YCgCo.exe
./LuvCH2YDbDr.exe
./LuvCH2yiq.exe
./LuvCH2YPbPr.exe
./LuvCH2YPbPr2020.exe
./LuvCH2YPbPr601.exe
./LuvCH2YPbPr709.exe
./LuvCH2yuv.exe
./LuvCH2yuv601.exe
./LuvCH2yuv709.exe